In [5]:
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction

## 3.4 这个神经网络做了什么?
将输入乘以权重,将输入"缩放"一定的比例.

In [6]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


In [11]:
weights = [0.1, 0.2, 0]

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
        
    return output

def neural_network(input, weight):
    pred = w_sum(input, weights)
    return pred

In [13]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weight)

print(pred)

0.9800000000000001


## NumPy 代码

In [1]:
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    //dot函数:点乘
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)
print(pred)

0.9800000000000001


## 3.8 预测多个输出

In [8]:
# 定义 ele_mul 函数
def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

# 定义 neural_network 函数
def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

# 定义权重和输入
weights = [0.3, 0.2, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]

# 调用 neural_network 函数并打印结果
pred = neural_network(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


## 3.9 使用多个输入和输出进行预测

In [16]:
weights = [ [0.1, 0.1, -0.3],
            [0.1, 0.2, 0.0],
            [0.0, 1.3, 0.1]]

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


## 3.11 用预测结果进一步预测

In [23]:
import numpy as np

ih_wgt = np.array([
    [0.1, 0.2, -0.1],
    [-0.1, 0.1, 0.9],
    [0.1, 0.4, 0.1]
])

hp_wgt = np.array([
    [0.3, 1.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 0.1]
])

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)
print(pred)

[ 0.496  1.256 -0.286]


## 3.12 NumPy快速入门

In [27]:
import numpy as np

a = np.array([0, 1, 2, 3]) #一个向量
b = np.array([4, 5, 6, 7]) #另一个向量
c = np.array([[0, 1, 2, 3],  #一个矩阵
              [4, 5, 6, 7]
             ])

d = np.zeros((2, 4))  # 2*4的全零矩阵
e = np.random.rand(2, 5) #2*5的随机矩阵,元素值再0 - 1之间

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.38159036 0.68556592 0.94706175 0.72064966 0.0586601 ]
 [0.47688729 0.41322412 0.934228   0.59755553 0.83321826]]


In [30]:
print(a * 0.1) #将向量a中每一个数字x0.1
print(c * 0.2) #将向量c中每一个数字x0.2
print(a * b) #对向量a 和 b执行逐元素乘法
print(a * b * 0.2) #执行逐元素乘法再x0.2
print(a * c) #对矩阵c的每一行执行逐元素乘法

#print(a * e) #列数不同->异常

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]
